import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/sessionprovider";
import { Toaster } from "@/components/ui/toaster";
import { HomePage } from "@/components/component/home-page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        {children}
        <Toaster />
      </Providers>
        </body>
    </html>
  );
}
